server:
  port: 8201

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messages
    username: admin
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    client-id: kafka-consumer

    listener:
      ack-mode: manual
      concurrency: 6
      log-container-config: false
      poll-timeout: 60000ms
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 50
      auto-commit-interval: 0


